### PR TITLE
Add typing and verbose

### PR DESCRIPTION
**Pull request by FuriouZz**

### CODE REVIEW

**Comment by mde** [comment]
This is great, but it adds several new hard dependencies, which is problematic because FileList is in Jake, which is used in the EJS CLI. EJS users are very sensitive to new deps being added. Is there any way to make sure these are only added as dev-deps?

**Comment by FuriouZz** [comment]
Mhm...no really sure to understand what do you mean by "new hard dependencies". There is no more dependencies in package.json at the exception of the addition of the `types` field.

**Comment by mde** [comment]
Ah, there we go. I was looking at the package-lock file. This is great, thank you so much!

**Comment by mde** [comment]
Published to NPM in v1.0.2

**Comment by FuriouZz** [comment]
@mde Oupsy...It was fast 😅. 

I just realize I can make the definitions more future proof (FileList directly extends Array<string>). And improve typings on `.include()` with the IncludeOptions from minimatch.

https://github.com/FuriouZz/filelist/blob/master/index.d.ts

**Comment by mde** [comment]
Sure, just submit me another PR. :)

**Pull request merged**
